# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3.95, max_digits=10),
        ),
    ]
