# Generated by Django 2.1.2 on 2019-01-18 02:57

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bookstore.models.upload_image_path),
        ),
    ]
